### ISSUE TITLE
Profile Provider?

### ISSUE THREAD

**Issue by scrappydog** [typemismatch/multicore#3]
Any thoughts about doing a profile provider in addition to membership and role?

**Comment by typemismatch** [comment]
Sure, it would be a good addition and should be simple enough with the easily expanded sdb schema - I'll try get a version into the current edge and then push out a release.

**Comment by typemismatch** [comment]
Hey, do you have any time to test the profile provider? I'll push it to the edge branch in the next couple hours, if it works ok I'll push a completed release. It will have all functionality in this version except for inactivity methods.

**Comment by scrappydog** [comment]
Cool!  I should be able to take a look at it this eveing....

**Comment by typemismatch** [comment]
Code is up in "edge" - wrote a quick tester, seems to work nicely. See the edge wiki page for any other instructions. Only stores strings at the moment.

**Comment by typemismatch** [comment]
rolled into 1.0.2.0 and released.
